name: CustomHitCommand
version: '${project.version}'
main: de.nicouschulas.customhitcommand.CustomHitCommand
api-version: 1.21
author: nicouschulas
description: Executes a configurable command when hitting an other player with a configurable specific item.
commands:
  chc:
    description: Reloads the CustomHitCommand plugin configuration.
    usage: /<command> reload | sethititem
    permission: customhitcommand.use
    permission-message: You don't have permission to use this command.
    aliases:
      - customhitcommand

permissions:
  customhitcommand.use:
    description: Allows a player to use all CustomHitCommand features.
    default: op
  customhitcommand.reload:
    description: Reloads the CustomHitCommand plugin configuration.
    default: op
  customhitcommand.sethititem:
    description: Allows a player to mark an item as the custom hit item.
    default: op